import os
import sys
import json
import subprocess
from PIL import Image
from google import genai
from google.genai import types
from pydantic import BaseModel, Field
from typing import List

# Define structured output schemas
class ReplacementChunk(BaseModel):
    target_content: str = Field(description="The exact block of code to search for in src/index.css. It must match the original content exactly, including whitespace.")
    replacement_content: str = Field(description="The new content to replace it with.")

class CSSModifications(BaseModel):
    explanation: str = Field(description="A brief explanation in German of what visual or layout issues were found in the screenshots and how this plan fixes them.")
    replacements: List[ReplacementChunk] = Field(description="List of chunks to replace inside src/index.css to fix the layout or styling issues. Return an empty list if no adjustments are needed.")

def run_ui_debugger():
    print("Running UI debugger to capture screenshots...")
    # First ensure the server is building and start the debugger
    subprocess.run(["npm", "run", "build"], check=True)
    res = subprocess.run(["node", "src/solver/debug_ui.js"], capture_output=True, text=True)
    if res.returncode != 0:
        print(f"Debugger execution failed:\n{res.stdout}\n{res.stderr}")
        raise Exception("Vite or Puppeteer debugger failed.")
    print("Screenshots captured successfully.")

def apply_css_replacements(css_path: str, replacements: List[ReplacementChunk]):
    with open(css_path, 'r', encoding='utf-8') as f:
        content = f.read()

    modified = False
    for chunk in replacements:
        target = chunk.target_content.strip()
        replacement = chunk.replacement_content

        # Try exact search
        if target in content:
            content = content.replace(target, replacement)
            print(f"Applied replacement chunk starting with:\n{target[:60]}...")
            modified = True
        else:
            # Fallback: try search without strict whitespace wrapping if exact fails
            cleaned_target = "\n".join([line.strip() for line in target.split("\n")])
            # Find closest match or warn
            print(f"WARNING: Target chunk not found in index.css. Skipping:\n{target[:120]}...")

    if modified:
        with open(css_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print("index.css updated on disk.")
    return modified

def analyze_screenshots_and_correct(api_key: str, artifact_dir: str, css_path: str):
    client = genai.Client(api_key=api_key)

    # Screenshot paths generated by debug_ui.js
    screenshot_paths = {
        "desktop_units": os.path.join(artifact_dir, "debug_09_units_added.png"),
        "mobile_roster": os.path.join(artifact_dir, "debug_10_mobile_roster.png"),
        "mobile_library": os.path.join(artifact_dir, "debug_11_mobile_library.png"),
        "mobile_status": os.path.join(artifact_dir, "debug_12_mobile_status.png")
    }

    # Load current index.css
    with open(css_path, 'r', encoding='utf-8') as f:
        current_css = f.read()

    # Load images
    images_parts = []
    for key, path in screenshot_paths.items():
        if os.path.exists(path):
            print(f"Loading screenshot: {path}")
            img = Image.open(path)
            images_parts.append(img)
        else:
            print(f"WARNING: Screenshot {path} not found.")

    if not images_parts:
        raise Exception("No screenshots found to analyze. Make sure the Vite dev server is running and debug_ui.js completes successfully.")

    prompt = f"""
Du bist ein exzellenter Webentwickler und UI/UX-Designer.
Hier sind vier Screenshots unserer Warhammer Army Builder Anwendung (1x Desktop-Ansicht, 3x Mobile-Ansichten für die verschiedenen Tabs) sowie der aktuelle Inhalt von `src/index.css`.

Deine Aufgabe ist es, die Screenshots genau zu analysieren und visuelle oder Layout-Mängel zu finden, die gegen unsere Design-Richtlinien verstoßen.
Design-Richtlinien:
1. Edles, düsteres Gothic-/Fantasy-Theme (vibrante Kontraste, edles Gold/Gelb, dunkle Panels, Pergament-Texte).
2. Hohe Lesbarkeit und Kontrast (kein grauer Text auf grauem Hintergrund).
3. Konsistente Ränder, Abstände und Paddings.
4. Mobilfreundlichkeit (keine abgeschnittenen Texte, Boxen oder Überläufe; funktionale Tab-Navigation am unteren Rand).

Schau dir insbesondere an:
- Ob Schriftgrößen, Abstände oder Kontraste in der mobilen Ansicht stimmen.
- Ob die Knöpfe und Slider auf Mobilgeräten leicht anklickbar und gut positioniert sind.
- Ob Texte oder Symbole überlappen.

Falls du Mängel findest, generiere eine Liste von Code-Ersetzungen (Such- und Ersetzungstext) für `src/index.css`, um diese zu beheben. Die Suchtexte müssen exakt Zeichen für Zeichen mit dem Inhalt in der bereitgestellten CSS-Datei übereinstimmen.

Hier ist der aktuelle Inhalt von `src/index.css`:
```css
{current_css}
```

Antworte ausschließlich im JSON-Format gemäß des vorgegebenen Schemas. Wenn das Layout und die Ästhetik bereits perfekt sind, gib eine leere Liste von Ersetzungen zurück.
"""

    print("Sending screenshots and CSS to Gemini for feedback...")
    response = client.models.generate_content(
        model='gemini-2.5-pro',
        contents=images_parts + [prompt],
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=CSSModifications,
            temperature=0.2,
        ),
    )

    result = CSSModifications.model_validate_json(response.text)
    return result

def main():
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("GEMINI_API_KEY environment variable is not set.")
        sys.exit(1)

    artifact_dir = "/Users/artkoenig/.gemini/antigravity/brain/4ceed881-e54c-42cb-a67b-6525918aecbb"
    css_path = "./src/index.css"

    max_iterations = 3
    print(f"Starting UX Self-Correction loop (max {max_iterations} iterations)...")

    for iteration in range(max_iterations):
        print(f"\n--- ITERATION {iteration + 1} ---")
        try:
            # 1. Run debugger to get latest screenshots
            run_ui_debugger()

            # 2. Call Gemini Vision API to analyze and generate suggestions
            analysis = analyze_screenshots_and_correct(api_key, artifact_dir, css_path)
            print(f"AI Feedback: {analysis.explanation}")

            if not analysis.replacements:
                print("Gemini reports that the UI/UX is optimal and meets all guidelines! Loop completed.")
                break

            # 3. Apply the modifications to the CSS file
            modified = apply_css_replacements(css_path, analysis.replacements)
            if not modified:
                print("No replacements were successfully applied. Stopping loop to prevent infinite runs.")
                break

            print("CSS modified. Restarting iteration to capture new screenshots and verify...")

        except Exception as e:
            print(f"Error during self-correction iteration: {e}")
            sys.exit(1)

    print("\nSelf-correction workflow finished.")

if __name__ == "__main__":
    main()
